# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db5e87879cc71ff85cd8d34c7b32e77944eed86c866fe40d10d249ba700823fa5df69f23ba88af9d4a06016bb11ce8476e4ddf9a53138e98db2d13a9f9e321c9

test:
  secret_key_base: 66b17c8a64187e82cff4bb1e73962a9e27de9b09db2c5c7c4e307042f3cf5f5f366b6d57cda15d14f4a9129c14cd45fc0b1f724e3b6f471e0928d168e79ca93d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
